### ISSUE TITLE
install is KO

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/pytition_ynh#16]
### Describe the bug

install fails

### Context

- Hardware: *VPS bought online*
- YunoHost version: 
```
yunohost -v
yunohost: 
  repo: stable
  version: 11.0.10.2
yunohost-admin: 
  repo: stable
  version: 11.0.11
moulinette: 
  repo: stable
  version: 11.0.9
ssowat: 
  repo: stable
  version: 11.0.9
  ```
- I have access to my server: Through SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- trying to install package version/branch: stable : Shipped version: 2.6~ynh1 (as said in the readme.md)

### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough. For example:*
    ```sh
    # yunohost app install pytition
    ```
### Expected behavior
i expected the install is ok, runlevel is 7:
 Integration level 7
 status Working 
 Maintenance status: maintaned

### Logs

https://paste.yunohost.org/raw/uyazabowij
```
Info: WARNING - The following packages have unmet dependencies:
Info: WARNING -  default-libmysqlclient-dev : Depends: libmariadb-dev-compat but it is not going to be installed
Info: WARNING -  libzip-dev : Depends: libzip4 (= 1.7.3-1) but 1.7.3-1+0~20210114.10+debian10~1.gbp4c125d is to be installed
Info: WARNING -  virtualenv : Depends: python3-virtualenv but it is not going to be installed
Info: DEBUG - + ynh_die '--message=Unable to install dependencies'
Info: WARNING - Unable to install dependencies
```

thx for your help

**Comment by isAAAc** [comment]
testing branch is failing too

**Comment by alexAubin** [comment]
It's probably unrelated to the app itself, this sounds related to an infamous issue with legacy system because of the libzip lib

You should `apt install libzip4=1.7.3-1` to unlock the situation

**Comment by Salamandar** [comment]
Yeah, I'm sorry @isAAAc I don't really know what's happening here. Get back to us if @alexAubin 's solution doesn't work.

**Comment by isAAAc** [comment]
thx @alexAubin @Salamandar 
install is OK <3

an other thing, (tell me if you prefer i open a new issue to track this)
the install request a password to manage the app, 
but what is the login to use it ?

**Comment by Salamandar** [comment]
@isAAAc For those kind of questions, you can come on Matrix or IRC at #yunohost:libera.chat :)
The username is admin. Although, it is not for the standard login, but for the admin dashboard, accessible at `https://yourdomain.tld/pytition/admin`
